# Generated by Django 2.2.7 on 2019-11-25 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('postBy', models.CharField(max_length=150)),
                ('publishDate', models.DateField(auto_now_add=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('readQuantity', models.IntegerField()),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsCategory.NewsCategory')),
            ],
        ),
    ]
